version: '2'

volumes:
  prometheus-storage:
  grafana-storage:

networks:
  metrics:
    external:
      name: monitor_byfn

services:
  # prometheus will pull metrics from fabric
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    restart: always
    tty: true
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    ports:
      - 9090:9090
    networks:
      - metrics

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    environment:
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./config/grafana_conf/hyperledger-fabric-monitoring-for-1.4.json:/var/lib/grafana/dashboards/dashboard.json
      - ./config/grafana_conf/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - metrics
    depends_on:
      - prometheus
