# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  peer-base:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Metrics section
      # metrics provider is one of statsd, prometheus, or disabled
      - CORE_METRICS_PROVIDER=${METRICS_PROVIDER}
      # network type: tcp or udp
      - CORE_METRICS_STATSD_NETWORK=udp
      - CORE_METRICS_STATSD_ADDRESS=graphite:8125
      - CORE_METRICS_STATSD_WRITEINTERVAL=10s
      - CORE_METRICS_STATSD_PREFIX=
      # Operations section
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
      - CORE_OPERATIONS_TLS_ENABLED=false
      - CORE_OPERATIONS_TLS_CERT_FILE=
      - CORE_OPERATIONS_TLS_KEY_FILE=
      - CORE_OPERATIONS_TLS_CLIENTAUTHREQUIRED=false
      - CORE_OPERATIONS_TLS_CLIENTROOTCAS_FILES=[]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start

  orderer-base:
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      # Metrics section
      # metrics provider is one of statsd, prometheus, or disabled
      - ORDERER_METRICS_PROVIDER=${METRICS_PROVIDER}
      # network type: tcp or udp
      - ORDERER_METRICS_STATSD_NETWORK=udp
      - ORDERER_METRICS_STATSD_ADDRESS=graphite:8125
      - ORDERER_METRICS_STATSD_WRITEINTERVAL=10s
      - ORDERER_METRICS_STATSD_PREFIX=
      # Operations section
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      - ORDERER_OPERATIONS_TLS_ENABLED=false
      - ORDERER_OPERATIONS_TLS_CERT_FILE=
      - ORDERER_OPERATIONS_TLS_KEY_FILE=
      - ORDERER_OPERATIONS_TLS_CLIENTAUTHREQUIRED=false
      - ORDERER_OPERATIONS_TLS_CLIENTROOTCAS_FILES=[]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
