apiVersion: 1

deleteDatasources:
  - name: 'Prometheus'
    orgId: 1
  - name: 'Graphite'
    orgId: 1
datasources:
  - name: 'Prometheus'
    type: 'prometheus'
    access: 'direct'
    orgId: 1
    url: 'http://prometheus:9090'
    isDefault: true
    version: 1
    editable: false
  - name: 'Graphite'
    type: 'graphite'
    access: 'proxy'
    orgId: 1
    url: 'http://graphite:8080'
    isDefault: false
    version: 1
    editable: false
